---
- name: HelloWorld
  hosts: all

  tasks:
  - name: "Installing repo telegraf"
    template: src=influxdb.repo dest=/etc/yum.repos.d/influxdb.repo
  - name: "Installing telegraf"
    yum:
      name: telegraf
      state: latest 
  - name: "Change config telegraf"
    loop: "{{ hostList }}"
    when: " item.hostname == ansible_hostname "
    template: src=telegraf.conf dest=/etc/telegraf/telegraf.conf
  - name: Reload service telegraf, in all cases
    service:
      name: telegraf
      state: reloaded
